version: '2'


services:
  elasticsearch:
    image: elasticsearch:alpine
    ports:
      - "9200"
      - "9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - werfty_tiktak
  logstash:
    image: logstash:alpine
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./volumes/logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"   # logstash/graylog
      - "5044:5044"   # beats
      - "5045:5045"   # json

    networks:
      - werfty_tiktak
    #depends_on:
    #  - elasticsearch
  kibana:
    image: kibana:latest
    volumes:
      - ./volumes/kibana/config/:/etc/kibana/
    ports:
      - "5601"
    networks:
      - werfty_tiktak
    depends_on:
      - elasticsearch
    environment:
      - ES_JAVA_OPTS="-Des.path.conf=/etc/elasticsearch"
    command: "-E network.host=0.0.0.0 -E discovery.zen.minimum_master_nodes=1"


  proxy:
    image: nginx:mainline-alpine
    volumes:
      - ./volumes/nginx/config/:/etc/nginx/
    ports:
      - "443"
      # - "80" unsecure access disabled by default
    networks:
      - werfty_tiktak
    depends_on:
      - kibana


networks:
  werfty_tiktak:
    driver: bridge
